# dataset
image_file: 'body'
dl_scale: 4
num_meas: 20000
angle_disc: 120
pdf: 'nonuniform'
fixed_pdf: True
batch_size: 50 #50
snr: 'inf' #0
pdf_known: False
a_size: 5 #4

# model
mid_size: 1024
tau: 0.5

# optimization
num_epoch: 30000
optimizer: 'sgd'
scheduler_x: 'step'
scheduler: 'step'
# initialization of the signal
init: 'rand'
n_disc: 4
lrate: 0.001 # increased the lrates by a factor of 10
lrate_x: 0.001
lrate_pdf: 0.0002
start_pdf: 0
wdecay: 0.
wdecay_x: 0.01
wdecay_pdf: 0.04 #0.01
iter_change_lr: 10000 #30k
iter_change_lr_x: 10000 #30k
gamma: 0.9
gamma_x: 0.9
lamb: 0.00001
tv_weight: 0.01
tv_pdf: 0.01 #0


seed: 0
exp_name: 'exp_body1_64_fixed_wedge0_snr0_a5_seed0' #'exp_body1_64_known_wedge0_sigma0'
